### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by AlexNova1555** [BullyHunter32/bSecure#8]
Hey man i'm getting those error and i dont know why
do you have maybe any idea?

[bsecure_13.11.2021] bad argument #3 to 'Add' (function expected, got string)
  1. hook_Add - lua/includes/modules/hook.lua:31
   2. Hook - addons/bsecure_13.11.2021/lua/bsecure/modules/logging/sh_bsecure_logging_init.lua:39
    3. unknown - addons/bsecure_13.11.2021/lua/bsecure/modules/regionrestrictions/sv_bsecure_regionrestrictions_logs.lua:2
     4. include - [C]:-1
      5. IncludeModules - addons/bsecure_13.11.2021/lua/autorun/bsecure_include.lua:73
       6. unknown - addons/bsecure_13.11.2021/lua/autorun/bsecure_include.lua:112

[bsecure_13.11.2021] bad argument #3 to 'Add' (function expected, got nil)
  1. Add - lua/includes/modules/hook.lua:31
   2. unknown - addons/bsecure_13.11.2021/lua/bsecure/modules/vgui/sv_bsecure_banrecords.lua:25
    3. include - [C]:-1
     4. IncludeModules - addons/bsecure_13.11.2021/lua/autorun/bsecure_include.lua:73
      5. unknown - addons/bsecure_13.11.2021/lua/autorun/bsecure_include.lua:112

**Comment by BullyHunter32** [comment]
i'm currently working on a rewrite of bsecure which will improve reliability & fix everything.

this project is almost 1 year old and some of it is a little scuffed.

as for your issue, i've just now made a quick commit which should've fixed it.
lmk if the issue reoccurss.

apologies for the extremely late response
